name: Lancer script Python pour vérifier les créneaux disponibles

on:
  schedule:
    # Exécution tous les jours à 00h45 UTC
    - cron: '45 10 * * *'
  workflow_dispatch: # Permet le déclenchement manuel depuis GitHub

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Exécuter le script Python
        working-directory: src
        run: python GenerateStoryFull.py